### ISSUE TITLE
Devise and Paranoia

### ISSUE THREAD

**Issue by michaelirick** [SandStormIT/all-your-rails-base#18]
This is something that I encountered on TIG. When you delete a devise model that acts_as_paranoid, you will not be able to add a new object with the same identifying attribute(email is default) as a deleted object. For TIG, I got around this by adding a migration to remove the unique index on email and add a regular index, then removing the validatable option from the devise options on the model and adding the validations(password and email by default) to the model directly making sure that the uniqueness is scoped to deleted_at.

**Comment by jordanbsanders** [comment]
Fixed in https://github.com/SandStormIT/all-your-rails-base/pull/22.
